require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Rails:
  Enabled: true

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': '[]'
    '%w': '[]'

Documentation:
  Enabled: false

Lint/ScriptPermission:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Exclude:
    - 'db/migrate/*'
    - 'spec/**/*'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

RSpec/NestedGroups:
  Max: 5

RSpec/AnyInstance:
  Exclude:
    - 'spec/backend/requests/contentful_controller_spec.rb'
    - 'spec/backend/lib/**/*'

Style/MixinUsage:
  Enabled: false

