language: ruby

cache:
  - bundler
  - yarn

rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.0
  - 2.5.1

before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - gem update --system

before_script:
  - cp config/database.yml.travis config/database.yml
  - cp config/secrets.yml.travis config/secrets.yml
  - psql -c 'create database travis_ci_test;' -U postgres

install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn

script:
  - bundle exec rake db:migrate
  - bundle exec rspec
  - yarn test:once

bundler_args: --without production

after_script:
  - ./cc-test-reporter after-build --exit-code $EXIT_CODE
